[package]
name = "libcheese"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
solana-sdk = "2.1.7"
solana-client = "2.1.7"
spl-associated-token-account = "6.0.0"
spl-token = "4.0.0"
bincode = "1.3"
base64 = "0.22.1"
lazy_static = "1.4.0"
