[package]
name = "libcheese"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
solana-sdk = "2.1.0"
solana-client = "2.1.0"
solana-zk-sdk = "2.1.0"
spl-associated-token-account = "4.0.0"
spl-token = "3.5.0"
bincode = "1.3"
base64 = "0.22.1"
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
bytemuck = "1.14"
zeroize = "1.7.0"
