[package]
name = "libcheese"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["rt-multi-thread", "macros"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
solana-sdk = "1.14"
solana-client = "1.14"
spl-associated-token-account = "1.1"
spl-token = "3.5"
solana-program = "1.14"
bincode = "1.3"
base64 = "0.22.1"
anchor-lang = { version = "0.26", features = ["init-if-needed"] }
prog-dynamic-amm = { git = "https://github.com/mercurial-finance/mercurial-dynamic-amm-sdk", branch = "master", package = "dynamic-amm" }
prog-dynamic-vault = { git = "https://github.com/mercurial-finance/mercurial-dynamic-amm-sdk", branch = "master", package = "dynamic-vault" }
