[package]
name = "cheese"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
reqwest = "0.12.11"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["macros"] }
