[package]
name = "cheese"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
reqwest = "0.12.11"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["macros"] }
bip39 = "2.1.0"
ed25519-dalek = "2.1.1"
k256 = "0.13.4"
rand_core = "0.6.4"
